# This is a simple workflow that demonstrates how to use Kestra to orchestrate tasks.
# It takes a name as input, generates a welcome message, and logs it.


id: 01_hello_world
namespace: zoomcamp

# Defines variables you can pass in the workflow.
inputs:
  - id: name      # A text field (STRING type)
    type: STRING
    defaults: Will  #if you don't provide a name, it will default to "Will".

#Controls how many copies of this workflow can run at once. 
concurrency:
  behavior: FAIL    # if a 3rd tries to start, if fails (doesn't queue)
  limit: 2          # Maximum 2 instances can run simultaneously. 


#Creates reusable variables within the workflow. 
variables:
  welcome_message: "Hello, {{ inputs.name }}!"   # A template that says "Hello, [name]!"  
  # Uses {{ }} syntax to insert values (like ${} in other languages)


#Defines the tasks that will be executed in this workflow. Each task has a unique ID and a type that specifies what it does.
tasks:
  - id: hello_message
    type: io.kestra.plugin.core.log.Log      # Type: Log plugin, prints to console/logs. Prints the welcome message.
    message: "{{ render(vars.welcome_message) }}"

# This task generates an output that can be used by the other tasks. Uses return plugin to create an output (I was generared during this workflow).
  - id: generate_output
    type: io.kestra.plugin.core.debug.Return
    format: I was generated during this workflow.

# This is the sleep plugin, pauses execution for a specified duration, here 15 seconds (PT15S = Period time 15 Seconds)
  - id: sleep
    type: io.kestra.plugin.core.flow.Sleep
    duration: PT15S

# This task logs a message that includes the output from the generate_output task. It demonstrates how to reference outputs from other tasks using {{ outputs.[task_id].[output_name] }} syntax.
  - id: log_output
    type: io.kestra.plugin.core.log.Log
    message: "This is an output: {{ outputs.generate_output.value }}"

# This task logs a goodbye message, demonstrating how to use the input variable again.
  - id: goodbye_message
    type: io.kestra.plugin.core.log.Log
    message: "Goodbye, {{ inputs.name }}!"

# sests default configuration for all log plugines in this workflow. Level:Error: Only shows ERROR messages (Hides INFO/WARN)
# This makes logs less verbose (quieter).
pluginDefaults:
  - type: io.kestra.plugin.core.log.Log
    values:
      level: ERROR

# Defines when the workflow runs automatically. 
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 10 * * *"                          # Runs daily at 10:00 AM (UTC time).
    inputs:
      name: Sarah                               # Automatically passes "Sarah" as the name.
    disabled: true                              # currently turned off (wont auto-run)


# The execution flow will be as follows:
# Start > hello_message > generate_output > sleep (15s) > log_output > goodbye_message > End.

# The key syntax patterns include:
# {{ inputs.name }} → Get input value
# {{ vars.variable_name }} → Get workflow variable
# {{ outputs.task_id.value }} → Get output from another task
# {{ render(...) }} → Process template text

# The data flow between tasks:
# Inputs → Come from outside (user/trigger)
# Variables → Internal reusable values
# Task Outputs → Pass data between tasks
# Final Output → Result of last task or specific output task

#The common plugine types:
# Log > Print messages
# Return > Generate output data
# Sleep > Wait/pause
# Schedule > Run on timer

#Important settings:
# disabled: true > turns off auto-execution
# defaults > Default value if input not provided
# concurrency > Controls how many instances can run at once